### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by konklone** [linzjax/linzjax.github.io#4]
GitHub now lets you enforce HTTPS for `*.github.io` domains:

https://github.com/blog/2186-https-for-github-pages

The site already works over HTTPS without errors: https://linzjax.github.io So this should be a trivial fix.

![support page](https://help.github.com/assets/images/help/pages/enforce-https-checkbox.png)

**Comment by linzjax** [comment]
That was surprisingly simple to fix. Thanks for the heads up!

**Comment by konklone** [comment]
Awesome, thanks! :smiley_cat:
